### ISSUE TITLE
unable to start GROMACS plugin

### ISSUE THREAD

**Issue by anu-bioinfo** [makson96/Dynamics#102]
Hello Tomasz,

I am having an issue with starting the GROMACS/Dynamics plugin on pymol. I get the following error:

Searching for GROMACS installation
Running command: gmx_mpi_d -version; STDIN: None; STDOUT: test_gromacs.txt
Running command: gmx_mpi -version; STDIN: None; STDOUT: test_gromacs.txt
Running command: gmx -version; STDIN: None; STDOUT: test_gromacs.txt
Warning. Unsupported GROMACS Version
Running command: gmx_mpi_d -version; STDIN: None; STDOUT: test_gromacs.txt
Running command: gmx_mpi -version; STDIN: None; STDOUT: test_gromacs.txt
Running command: gmx -version; STDIN: None; STDOUT: test_gromacs.txt
Reading available force fields and water models
Running command: gmx pdb2gmx -f test_gromacs.pdb -o test_gromacs.gro -p test_gromacs.top; STDIN: gromacs_stdin.txt; STDOUT: test_gromacs.txt
Reading available groups
Running command: gmx trjconv -f  test_gromacs.pdb -s test_gromacs.pdb -o test_gromacs2.pdb; STDIN: gromacs_stdin.txt; STDOUT: test_gromacs.txt
Found GROMACS VERSION 2021.1-MODIFIED
Traceback (most recent call last):
  File "/mnt/NewHDD/anaconda3/envs/pymol/lib/python3.8/site-packages/pmg_tk/startup/pymol_plugin_dynamics.py", line 197, in init_function
    create_gui(gui_library, status, simulation_parameters, parent)
  File "/mnt/NewHDD/anaconda3/envs/pymol/lib/python3.8/site-packages/pmg_tk/startup/pymol_plugin_dynamics.py", line 1651, in create_gui
    root_window(status, s_parameters, parent)
  File "/mnt/NewHDD/anaconda3/envs/pymol/lib/python3.8/site-packages/pmg_tk/startup/pymol_plugin_dynamics.py", line 1715, in root_window
    water_nr = gromacs.water_list[0][0]
IndexError: list index out of range

Could you please help me out with this ? Thanks in advance for any help.

Regards,

Anupam

**Comment by dsanmiguel** [comment]
Also having this issue. Cannot run plugin at all.
